# Generated by Django 5.2.12 on 2026-03-21 09:45

import notes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="cover",
            field=models.ImageField(
                blank=True, null=True, upload_to=notes.models.cover_upload_path
            ),
        ),
        migrations.AddField(
            model_name="note",
            name="cover_thumbnail",
            field=models.ImageField(
                blank=True, null=True, upload_to=notes.models.cover_upload_path
            ),
        ),
    ]
